/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JDialog;

import Base_de_Datos.conexion;
import Jpanel.Usuario;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author thomy
 */
public class mi_perfil extends javax.swing.JDialog {

    conexion objcon = new conexion();
    ArrayList<String> lista = new ArrayList<>();
    
    String nombre,
           apellido,
           cedula,
           correo,
           telefono,
           usuario,
           posicion,
           pass,
           pass_conf,
           sql;
    Usuario mUsuario = Usuario.getUsuario();
    String usu;
    boolean paso= true;
    
    public mi_perfil(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
       
        objcon.crearConexion();       
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_nombre = new javax.swing.JLabel();
        jLabel_apellido = new javax.swing.JLabel();
        jLabel_cedula = new javax.swing.JLabel();
        jLabel_correo = new javax.swing.JLabel();
        jLabel_celular = new javax.swing.JLabel();
        jButton_aplicarCambios = new javax.swing.JButton();
        jButton_cerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel_usuario = new javax.swing.JLabel();
        jLabel_pass = new javax.swing.JLabel();
        jTF_usuario = new javax.swing.JTextField();
        jLabel_passConfirm = new javax.swing.JLabel();
        jTF_confirmar = new javax.swing.JPasswordField();
        jTF_pass = new javax.swing.JPasswordField();
        jTF_nombre = new javax.swing.JTextField();
        jTF_apellido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFTF_cedula = new javax.swing.JFormattedTextField();
        jTF_correo = new javax.swing.JTextField();
        jFTF_telefono = new javax.swing.JFormattedTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_nombre.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_nombre.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_nombre.setText("Nombre");

        jLabel_apellido.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_apellido.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_apellido.setText("Apellido");

        jLabel_cedula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_cedula.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_cedula.setText("Cedula");

        jLabel_correo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_correo.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_correo.setText("Correo");

        jLabel_celular.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_celular.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_celular.setText("Telefono/Celular");

        jButton_aplicarCambios.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_aplicarCambios.setForeground(new java.awt.Color(0, 102, 255));
        jButton_aplicarCambios.setText("Aplicar Cambios");
        jButton_aplicarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aplicarCambiosActionPerformed(evt);
            }
        });

        jButton_cerrar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton_cerrar.setForeground(new java.awt.Color(0, 102, 255));
        jButton_cerrar.setText("Cerrar");
        jButton_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cerrarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(java.awt.Color.white);
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario y Contraseña para el Sistema", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14), new java.awt.Color(0, 102, 255))); // NOI18N

        jLabel_usuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_usuario.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_usuario.setText("Usuario");

        jLabel_pass.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_pass.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_pass.setText("Contraseña");

        jTF_usuario.setEditable(false);
        jTF_usuario.setBackground(new java.awt.Color(255, 255, 255));
        jTF_usuario.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel_passConfirm.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel_passConfirm.setForeground(new java.awt.Color(0, 102, 255));
        jLabel_passConfirm.setText("Confirmar");

        jTF_confirmar.setEditable(false);
        jTF_confirmar.setBackground(new java.awt.Color(255, 255, 255));

        jTF_pass.setEditable(false);
        jTF_pass.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_usuario)
                    .addComponent(jLabel_passConfirm)
                    .addComponent(jLabel_pass))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTF_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jTF_confirmar)
                    .addComponent(jTF_usuario))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_usuario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pass)
                    .addComponent(jTF_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_passConfirm)
                    .addComponent(jTF_confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTF_nombre.setEditable(false);
        jTF_nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTF_nombre.setBorder(null);

        jTF_apellido.setEditable(false);
        jTF_apellido.setBackground(new java.awt.Color(255, 255, 255));
        jTF_apellido.setBorder(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/perfil.png"))); // NOI18N

        jFTF_cedula.setEditable(false);
        jFTF_cedula.setBackground(new java.awt.Color(255, 255, 255));
        jFTF_cedula.setBorder(null);
        try {
            jFTF_cedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_cedula.setCaretPosition(0);

        jTF_correo.setEditable(false);
        jTF_correo.setBackground(new java.awt.Color(255, 255, 255));
        jTF_correo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTF_correo.setBorder(null);

        jFTF_telefono.setEditable(false);
        jFTF_telefono.setBackground(new java.awt.Color(255, 255, 255));
        jFTF_telefono.setBorder(null);
        try {
            jFTF_telefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFTF_telefono.setToolTipText("");
        jFTF_telefono.setCaretPosition(0);

        jPanel3.setBackground(new java.awt.Color(0, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 136, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 141, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 109, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_cedula)
                            .addComponent(jLabel_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel_apellido))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jFTF_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                                        .addComponent(jLabel_correo)))
                                .addGap(15, 15, 15)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTF_correo))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addComponent(jLabel8)
                        .addGap(51, 51, 51))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_celular)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFTF_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jButton_aplicarCambios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(164, 164, 164))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel_nombre)
                                    .addComponent(jLabel_apellido)
                                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTF_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_cedula)
                            .addComponent(jLabel_correo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jFTF_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTF_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel8)))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel_celular)
                        .addComponent(jFTF_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_aplicarCambios, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //METODO PARA OBTENER LOS DATOS DEL USUARIO
    public final void DatosUsuario(String sql) {

        try {

            objcon.ejecutarSQLSelect(sql);

            conexion.resultado.first();

            nombre = conexion.resultado.getString(1);
            apellido = conexion.resultado.getString(2);
            cedula = conexion.resultado.getString(3);
            correo = conexion.resultado.getString(4);
            telefono = conexion.resultado.getString(5);
            usuario = conexion.resultado.getString(6);
            pass = conexion.resultado.getString(7);
            usu = mUsuario.getUsu();
            
            if (paso){
                 paso = false;
                 posicion = conexion.resultado.getString("Posicion");

            }
           
            setDatos();

        } catch (SQLException ex) {

            Logger.getLogger(ver_usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//Fin Datos Usuarios

    //METODO PARA ESTABLECER DATOS EN EL DIALOG
    public final void setDatos() {

        jTF_nombre.setText(nombre);
        jTF_apellido.setText(apellido);
        jFTF_cedula.setText(cedula);
        jTF_correo.setText(correo);
        jFTF_telefono.setText(telefono);
        jTF_usuario.setText(usuario);
        jTF_pass.setText(pass);

        jTF_usuario.setEditable(false);
        jTF_pass.setEditable(false);
        jTF_confirmar.setEditable(false);

        if (posicion.equalsIgnoreCase("Administrador")) {

            jTF_nombre.setEditable(true);
            jTF_apellido.setEditable(true);
            jFTF_cedula.setEditable(true);
            jFTF_telefono.setEditable(true);
            jTF_correo.setEditable(true);


            if (usuario.equalsIgnoreCase(usu)) {
                
                jTF_pass.setEditable(true);
                jTF_confirmar.setEditable(true);

            }

        }
        if (posicion.equalsIgnoreCase("Asistente")) {


            jTF_pass.setEditable(true);
            jTF_confirmar.setEditable(true);
            jFTF_telefono.setEditable(true);
            jTF_correo.setEditable(true);

        }

    }//FIN METODO PARA ESTABLECER DATOS
    
    public void ActualizaDatos(String correo, String telefono, String pass,String cedula) throws SQLException{
            
            sql = "UPDATE empleados AS e INNER JOIN usuarios AS u on e.id_empleado = u.id_empleado SET "
                        + "    e.correo_empleado = '" + correo + "' , e.telefono_empleado = '" + telefono 
                        + "',  u.contrasena_usuario = '" + pass + "' WHERE e.cedula_empleado = '" + cedula + "'";
                objcon.ejecutarSQL(sql);
                
                if(objcon.resultado.first()){
                    
                    JOptionPane.showConfirmDialog(null, "Datos Actualizados con exito", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);
               
                }
    }
    
    /*public void ActualizaDatosAdmins(String nombre, String apellido, String cedula, String correo, String telefono, String pass, String pass_conf) {

        if (nombre.isBlank() || apellido.isBlank() || cedula.isBlank() || correo.isBlank() || telefono.isBlank() || usuario.isBlank() || pass.isBlank()) {

            JOptionPane.showMessageDialog(null, "Todos los campos deben estar completados", "Campos Incompletos", JOptionPane.ERROR_MESSAGE);
        } else {

            if (pass.equals(pass_conf)) {

                sql = "UPDATE empleados (nombre_empleado,apellido_empleado,cedula_empleado,correo_empleado,telefono_empleado) VALUES ('"
                        + nombre + "', '" + apellido + "', '" + cedula + "', '" + correo + "', '" + telefono + "')";
                objcon.ejecutarSQL(sql);

                try {

                    conexion.resultado.first();

                    int id_empleado = conexion.resultado.getInt("ID");

                    sql = "INSERT INTO usuarios (usuario,contrasena_usuario,id_empleado,Posicion,Estado) VALUES ('" + usuario + "', '" + pass + "', '" + id_empleado + "', '" + posicion + "', 'Activo')";
                    objcon.ejecutarSQL(sql);

                    JOptionPane.showMessageDialog(null, "Usuario Registrado Exitosamente!");

                } catch (SQLException ex) {

                    Logger.getLogger(registrar_usuario.class.getName()).log(Level.SEVERE, null, ex);
                }

            } else {

                JOptionPane.showMessageDialog(null, "Las contraseñas no coinciden", "ERROR", JOptionPane.ERROR_MESSAGE);
            }

        }

    }*/
    
    private void jButton_aplicarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aplicarCambiosActionPerformed
        try {
            // TODO add your handling code here:
            
            correo = jTF_correo.getText();
            telefono = jFTF_telefono.getText();
            pass = jTF_pass.getText();
            pass_conf = jTF_confirmar.getText();
            cedula = jFTF_cedula.getText();
            
            ActualizaDatos(correo,telefono,pass,cedula);
            
        } catch (SQLException ex) {
            Logger.getLogger(mi_perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton_aplicarCambiosActionPerformed

    private void jButton_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cerrarActionPerformed
        // TODO add your handling code here:
        
        this.setVisible(false);
    }//GEN-LAST:event_jButton_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mi_perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mi_perfil dialog = new mi_perfil(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aplicarCambios;
    private javax.swing.JButton jButton_cerrar;
    private javax.swing.JFormattedTextField jFTF_cedula;
    private javax.swing.JFormattedTextField jFTF_telefono;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_apellido;
    private javax.swing.JLabel jLabel_cedula;
    private javax.swing.JLabel jLabel_celular;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_pass;
    private javax.swing.JLabel jLabel_passConfirm;
    private javax.swing.JLabel jLabel_usuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTF_apellido;
    private javax.swing.JPasswordField jTF_confirmar;
    private javax.swing.JTextField jTF_correo;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JPasswordField jTF_pass;
    private javax.swing.JTextField jTF_usuario;
    // End of variables declaration//GEN-END:variables
}
